### ISSUE TITLE
npm install v1.42

### ISSUE THREAD

**Issue by Arthey** [alisahinozcelik/angular2-viewport#6]
Hey, 
first of all, thanks for that awesome package!

I have installed it via npm, but there is only the version 1.3.0 available.

Can you please update the Packages?

```
npm ERR! notarget No compatible version found: angular2-viewport@1.4.2
npm ERR! notarget Valid install targets:
npm ERR! notarget 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.3.0
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.
```

**Comment by alisahinozcelik** [comment]
Hi @Arthey , thanks a lot,

Nowadays I can not spend time on this project, sorry for that and I haven't tested my last commits on a browser.

However, I have published a beta version for you.
```npm install angular2-viewport@1.4.3```
